# Generated by Django 4.1 on 2022-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagecateagory",
            name="category_description",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
