# Generated by Django 4.1 on 2022-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_packagecateagory_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flename', models.CharField(max_length=100)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
