# Generated by Django 4.1.1 on 2022-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_client_email_client_first_name_client_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoot",
            name="package",
        ),
        migrations.AddField(
            model_name="shoot",
            name="package",
            field=models.ManyToManyField(to="shop.package"),
        ),
    ]
