# Generated by Django 4.1.1 on 2022-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_shoot_package_shoot_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoot",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
