# Generated by Django 4.1.1 on 2022-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_shoot_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoot",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
