# Generated by Django 4.1.1 on 2022-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_transaction_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
