# Generated by Django 4.1.1 on 2022-09-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_transaction_phone_number_transaction_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="request_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
