# Generated by Django 4.1.1 on 2022-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_transaction_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
