# Generated by Django 4.1.1 on 2022-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_transaction_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoot",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
