# Generated by Django 4.1.1 on 2022-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_shoot_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
