# Generated by Django 4.1.1 on 2022-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_transaction_viewed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=300)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
