# Generated by Django 4.1.1 on 2023-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_mymessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["-id"]},
        ),
    ]
