# Generated by Django 4.1.1 on 2023-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_service_alter_galleryimage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
