# Generated by Django 4.1.1 on 2023-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_servicecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ManyToManyField(to="shop.servicecategory"),
        ),
    ]
