# Generated by Django 4.1.1 on 2023-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoot",
            name="package",
        ),
        migrations.AddField(
            model_name="shoot",
            name="description",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoot",
            name="services",
            field=models.ManyToManyField(to="shop.service"),
        ),
    ]
