# Generated by Django 4.1.1 on 2023-05-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_remove_shoot_package_shoot_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="quantifiable",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BookedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.service",
                    ),
                ),
            ],
        ),
    ]
