# Generated by Django 4.1.1 on 2023-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_service_quantifiable_bookedservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoot",
            name="services",
        ),
        migrations.AddField(
            model_name="shoot",
            name="booked_services",
            field=models.ManyToManyField(to="shop.bookedservice"),
        ),
    ]
