# Generated by Django 4.1.1 on 2023-05-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_remove_shoot_services_shoot_booked_services"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-id"]},
        ),
    ]
