# Generated by Django 4.1.1 on 2023-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_remove_transaction_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order_tracking_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
